syntax = "proto2";

message bank_transactions {
	optional string transaction_id = 1;
	optional string sender_account_id = 2;
	optional string sender_name = 3;
	optional string sender_bank = 4;
	optional string receiver_account_id = 5;
	optional string receiver_name = 6;
	optional string receiver_bank = 7;
	optional string transfer_type = 8;
	optional double amount = 9;
	optional string currency = 10;
	optional string channel = 11;
	optional string memo = 12;
	optional bool is_international = 13;
	optional int32 sender_account_age_days = 14;
	optional double sender_avg_daily_amount = 15;
	optional int32 sender_transaction_count_24h = 16;
	optional string sender_ip_address = 17;
	optional double sender_latitude = 18;
	optional double sender_longitude = 19;
	optional string sender_city = 20;
	optional string sender_country = 21;
	optional string sender_region = 22;
	optional double receiver_latitude = 23;
	optional double receiver_longitude = 24;
	optional string receiver_city = 25;
	optional string receiver_country = 26;
	optional string receiver_region = 27;
	optional double distance_km = 28;
	optional string sender_device_id = 29;
	optional string sender_device_os = 30;
	optional int64 event_time = 31;
}
