# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bank_transactions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bank_transactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62\x61nk_transactions.proto\"\x85\x06\n\x11\x62\x61nk_transactions\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x19\n\x11sender_account_id\x18\x02 \x01(\t\x12\x13\n\x0bsender_name\x18\x03 \x01(\t\x12\x13\n\x0bsender_bank\x18\x04 \x01(\t\x12\x1b\n\x13receiver_account_id\x18\x05 \x01(\t\x12\x15\n\rreceiver_name\x18\x06 \x01(\t\x12\x15\n\rreceiver_bank\x18\x07 \x01(\t\x12\x15\n\rtransfer_type\x18\x08 \x01(\t\x12\x0e\n\x06\x61mount\x18\t \x01(\x01\x12\x10\n\x08\x63urrency\x18\n \x01(\t\x12\x0f\n\x07\x63hannel\x18\x0b \x01(\t\x12\x0c\n\x04memo\x18\x0c \x01(\t\x12\x18\n\x10is_international\x18\r \x01(\x08\x12\x1f\n\x17sender_account_age_days\x18\x0e \x01(\x05\x12\x1f\n\x17sender_avg_daily_amount\x18\x0f \x01(\x01\x12$\n\x1csender_transaction_count_24h\x18\x10 \x01(\x05\x12\x19\n\x11sender_ip_address\x18\x11 \x01(\t\x12\x17\n\x0fsender_latitude\x18\x12 \x01(\x01\x12\x18\n\x10sender_longitude\x18\x13 \x01(\x01\x12\x13\n\x0bsender_city\x18\x14 \x01(\t\x12\x16\n\x0esender_country\x18\x15 \x01(\t\x12\x15\n\rsender_region\x18\x16 \x01(\t\x12\x19\n\x11receiver_latitude\x18\x17 \x01(\x01\x12\x1a\n\x12receiver_longitude\x18\x18 \x01(\x01\x12\x15\n\rreceiver_city\x18\x19 \x01(\t\x12\x18\n\x10receiver_country\x18\x1a \x01(\t\x12\x17\n\x0freceiver_region\x18\x1b \x01(\t\x12\x13\n\x0b\x64istance_km\x18\x1c \x01(\x01\x12\x18\n\x10sender_device_id\x18\x1d \x01(\t\x12\x18\n\x10sender_device_os\x18\x1e \x01(\t\x12\x12\n\nevent_time\x18\x1f \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bank_transactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANK_TRANSACTIONS']._serialized_start=28
  _globals['_BANK_TRANSACTIONS']._serialized_end=801
# @@protoc_insertion_point(module_scope)
